name: Automerge

on:
  pull_request_target:
  push:
    branches:
      - main
    types:
      - opened
      - synchronized
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Automerge / auto-merge (pull_request_target)
        conclusion: neutral
        output: |
          {"summary": "Disregard - please see new automerge" }
